"""Variables that are needed in multiple files and don't change."""

# Screen

SCREEN_TITLE = "PyWeek 36"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Physics

GRAVITY = 1500

DEFAULT_DAMPING = 1.0
PLAYER_DAMPING = 0.4

PLAYER_FRICTION = 1.0
WALL_FRICTION = 0.7
DYNAMIC_ITEM_FRICTION = 0.6

PLAYER_MAX_HORIZONTAL_SPEED = 450
PLAYER_MAX_VERTICAL_SPEED = 1600

PLAYER_MOVE_FORCE_ON_GROUND = 8000
PLAYER_MOVE_FORCE_IN_AIR = 900

PLAYER_JUMP_IMPULSE = 1800
